#!/system/bin/sh
# Project WIPE https://github.com/yc9559/cpufreq-interactive-opt
# Author: yc9559
# Generated at: Sat Apr 14 17:22:50 2018
setenforce 0
action=$1

# Perfd
# ref: https://forum.xda-developers.com/showpost.php?p=68703199&postcount=4976
perfd_running=$(getprop "init.svc.perfd")
if [ "$perfd_running" = "running" ]; then
	# Stop perfd while tuning parameters
	stop perfd
fi

# HMP
echo 90 > /proc/sys/kernel/sched_spill_load
if [ -f /proc/sys/kernel/sched_boost]; then
	echo 0 > /proc/sys/kernel/sched_boost
fi
if [ -f /proc/sys/kernel/sched_prefer_sync_wakee_to_waker]; then
	echo 1 > /proc/sys/kernel/sched_prefer_sync_wakee_to_waker
fi
if [ -f /proc/sys/kernel/sched_init_task_load]; then
	echo 40 > /proc/sys/kernel/sched_init_task_load
fi

# THERMAL CONTROL
echo N > /sys/module/msm_thermal/parameters/enabled

# INPUT BOOST
echo 50 > /sys/module/cpu_boost/parameters/input_boost_ms

# disable thermal bcl hotplug to switch governor
echo 0 > /sys/module/msm_thermal/core_control/enabled

# set min & max frequency
echo 380000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /sys/devices/system/cpu/cpu4/online
echo 380000 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_min_freq

# shared interactive parameters
# echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
# echo 20000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_rate
echo 180000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack
echo 180000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/timer_slack
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/io_is_busy
echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/io_is_busy
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/ignore_hispeed_on_notif
echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/ignore_hispeed_on_notif

if [ "$action" = "powersave" ]; then
	echo "0:1280000 4:0" > /sys/module/cpu_boost/parameters/input_boost_freq
	echo "38000 1480000:18000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
	echo 1280000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
	echo "48 780000:56 880000:72 1180000:81 1280000:97" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
	echo "58000 1380000:78000 1680000:58000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
	echo 1280000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
	echo 98 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/boostpulse_duration
	echo "2 480000:36 680000:42 780000:65 880000:85 1180000:96" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time
fi

if [ "$action" = "balance" ]; then
	echo "0:1280000 4:0" > /sys/module/cpu_boost/parameters/input_boost_freq
	echo "38000 1480000:18000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
	echo 1280000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
	echo "51 680000:43 780000:55 880000:69 1180000:80 1280000:92" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
	echo "78000 1680000:38000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
	echo 1380000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/boostpulse_duration
	echo "22 480000:44 680000:59 780000:70 880000:98 1280000:94 1380000:99" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time
fi

if [ "$action" = "performance" ]; then
	echo "0:1280000 4:0" > /sys/module/cpu_boost/parameters/input_boost_freq
	echo "38000 1480000:18000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
	echo 1280000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
	echo "49 680000:44 780000:51 880000:63 1180000:71 1480000:60" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
	echo "78000 1680000:38000" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/above_hispeed_delay
	echo 1380000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/hispeed_freq
	echo 97 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/boostpulse_duration
	echo "12 480000:37 780000:59 880000:82 1180000:94 1280000:98" > /sys/devices/system/cpu/cpu4/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu4/cpufreq/interactive/min_sample_time
fi

if [ "$action" = "fast" ]; then
	# nothing
fi

# re-enable thermal bcl hotplug to switch governor
echo 1 > /sys/module/msm_thermal/core_control/enabled

exit 0