#!/system/bin/sh
# Project WIPE https://github.com/yc9559/cpufreq-interactive-opt
# Author: yc9559
# Generated at: Thu Apr 12 13:45:50 2018
setenforce 0
action=$1

# HMP
if [ -f /proc/sys/kernel/sched_boost]; then
	echo 0 > /proc/sys/kernel/sched_boost
fi
if [ -f /proc/sys/kernel/sched_prefer_sync_wakee_to_waker]; then
	echo 1 > /proc/sys/kernel/sched_prefer_sync_wakee_to_waker
fi
if [ -f /proc/sys/kernel/sched_init_task_load]; then
	echo 40 > /proc/sys/kernel/sched_init_task_load
fi
if [ -f /proc/sys/kernel/sched_spill_load]; then
	echo 90 > /proc/sys/kernel/sched_spill_load
fi
# THERMAL CONTROL
echo N > /sys/module/msm_thermal/parameters/enabled
# INPUT BOOST
echo 50 > /sys/module/cpu_boost/parameters/input_boost_ms

# disable thermal bcl hotplug to switch governor
echo 0 > /sys/module/msm_thermal/core_control/enabled

# set min & max frequency
echo 280000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /sys/devices/system/cpu/cpu2/online
echo 280000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq

# shared interactive parameters
echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_rate
echo 20000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/timer_rate
echo 180000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/timer_slack
echo 180000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/timer_slack
echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/ignore_hispeed_on_notif
echo 0 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/ignore_hispeed_on_notif

if [ "$action" = "powersave" ]; then
    echo "0:1380000 4:0" > /sys/module/cpu_boost/parameters/input_boost_freq
	echo "18000 1480000:78000 1580000:58000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
	echo 1380000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
	echo "1 480000:48 680000:55 780000:75 1080000:96" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
	echo "18000 1280000:38000 1480000:18000 1580000:78000 1780000:138000" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/above_hispeed_delay
	echo 1180000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/boostpulse_duration
	echo "1 480000:57 580000:31 680000:58 780000:77 980000:72 1080000:86 1180000:97 1280000:83 1480000:94 1680000:98" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/min_sample_time
fi

if [ "$action" = "balance" ]; then
    echo "0:1380000 4:0" > /sys/module/cpu_boost/parameters/input_boost_freq
	echo "18000 1480000:78000 1580000:58000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
	echo 1380000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
	echo "1 480000:42 680000:54 780000:75 980000:66 1080000:82 1180000:96 1280000:91 1380000:99 1580000:95" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
	echo "18000 1580000:78000 1780000:138000" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/above_hispeed_delay
	echo 1380000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/boostpulse_duration
	echo "1 480000:39 580000:49 680000:55 780000:75 1080000:88 1180000:99 1280000:83 1480000:94 1680000:98" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/min_sample_time
fi

if [ "$action" = "performance" ]; then
    echo "0:1480000 4:0" > /sys/module/cpu_boost/parameters/input_boost_freq
	echo "78000" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/above_hispeed_delay
	echo 1480000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/hispeed_freq
	echo 98 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/boostpulse_duration
	echo "1 480000:34 580000:45 780000:65 1180000:92 1280000:82 1380000:87 1480000:95" > /sys/devices/system/cpu/cpu0/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu0/cpufreq/interactive/min_sample_time
	echo "78000 1680000:58000" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/above_hispeed_delay
	echo 1580000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/hispeed_freq
	echo 99 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/go_hispeed_load
	echo 18000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/boostpulse_duration
	echo "1 480000:50 680000:18 780000:74 980000:61 1080000:76 1180000:96 1380000:79 1480000:98" > /sys/devices/system/cpu/cpu2/cpufreq/interactive/target_loads
	echo 18000 > /sys/devices/system/cpu/cpu2/cpufreq/interactive/min_sample_time
fi

if [ "$action" = "fast" ]; then
	# nothing
fi

# re-enable thermal bcl hotplug to switch governor
echo 1 > /sys/module/msm_thermal/core_control/enabled

exit 0